### PR TITLE
Add info about left calculation method

### PR DESCRIPTION
**Pull request by ahmadyusuf**
Added a comment to use the left calculation method if the house has solar panels installed as the default trapezoidal calculates wrong values if the consumpiton is 0 for an extended period of time

### CODE REVIEW

**Comment by ahmadyusuf** [comment]
Please refer to
https://github.com/klaasnicolaas/home-assistant-glow/issues/274

**Comment by klaasnicolaas** [comment]
I would prefer to omit the comment piece and include it in the FAQ

**Comment by ahmadyusuf** [comment]
Sure, will do that
Thank you

**Comment by klaasnicolaas** [comment]
Closing the PR wouldn't really have been necessary, you can just make and push a commit 😅

**Comment by ahmadyusuf** [comment]
Done, sorry I am new to this

**Comment by klaasnicolaas** [comment]
Could you perhaps convert this FAQ to the new format on the documentation website, these will no longer go into the readme file.

**Comment by ahmadyusuf** [comment]
Sure, I will close this pull request as the branch was out of sync and created a new one

https://github.com/klaasnicolaas/home-assistant-glow/pull/392

**Pull request closed without merging**
