### PR TITLE
add integrated case for esp32-wroom-32d

### PR DESCRIPTION
**Pull request by knaak**
I created this case for myself in order to have an integrated solution which is enclosed so I could mount it outside in the elements on my Elster R1S.  It features a downward facing LED housing which seals around the base of the LED, and an flashing around a USB cable which fits the cable snugly.  Finally, the light sensor fits with enough space for double sided tape to ensure a tight fit and good readings.

### CODE REVIEW

**Comment by knaak** [comment]
I am not too familiar with github and can't figure out how to add a label.

**Comment by klaasnicolaas** [comment]
Only I can assign labels 😉

**Comment by jascdk** [comment]
Nice - any pictures of the finished print and setup?

**Comment by knaak** [comment]
I added two photos here:  https://imgur.com/a/6Lc26SF

**Comment by klaasnicolaas** [comment]
There have been some changes recently, so the cases now have a new place on the documentation website. Could you adjust it so that it can eventually be merged?

https://glow-energy.io/docs/reference/cases

**Comment by knaak** [comment]
Can you clarify if you'd like me to edit the wiki to refer to the assets in the PR or something else?

**Comment by klaasnicolaas** [comment]
You need to change this file: https://github.com/klaasnicolaas/home-assistant-glow/blob/main/docs/docs/reference/cases.mdx
The assets can be placed in a seperate folder here: https://github.com/klaasnicolaas/home-assistant-glow/tree/main/docs/static/cases

You could copy and adapt the approach / description of the current case that I have posted.

**Pull request closed without merging**
