### PR TITLE
Fix For Installation

### PR DESCRIPTION
**Pull request by RamblingGeekUK**
This seems to be working for me now.   I have go through the install process a few times and it works for me.

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
These are a lot of different changes together and I can't merge them like that.

**Comment by RamblingGeekUK** [comment]
Ok, no worries. How would you like me to update ?

**Comment by RamblingGeekUK** [comment]
image

image

**Comment by klaasnicolaas** [comment]
I need to make some structural changes to the repo first, considering making `main` default branch. But I also see a lot of changes in your pull request that are unrelated or incorrect.

**Comment by RamblingGeekUK** [comment]
Ok.  I don't believe there are any errors as yaml complains, esp32 doesn't compile it when there are errors, so it wouldn't be working for me and I did follow the ESPHome documentation  https://esphome.io/guides/creators.html 

I do make use of the secrets.yaml.. which could cause some confusion. 

I was just trying to help.

**Comment by klaasnicolaas** [comment]
I understand that and your help is certainly appreciated ❤️ 
But for now I'll "park" your pull request and go through it again later to see if there are really changes that are useful.

**Comment by RamblingGeekUK** [comment]
Ok.   I think there have been some changes to the installation process.  Connect a device, it configures it as a basic YAML, then paste, then YAML, and it works.  Maybe that's the biggest change since the initial implementation.   

Thank you for doing this project, its been awesome for me.

**Comment by RamblingGeekUK** [comment]
I have tested what I said above.   Your YAML works fine. LOL!   It's the installation process in the existing readme that confused the hecc out of me :-)   No need to copy it to the ESPHome Folder.   

- New ESP32 goto ESPWeb and flash with ESPHome, connect to wifi.
- Edit the config, copy and paste your config over the top
- Update Wifi Details.
- Install
- Download the BIN file.
- Go back to the ESPHome Web and flash it on
- Home Assistant Detects it as version 3.1.0 
-

**Pull request closed without merging**
